# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    app.twig_extension_glyph:
        class: AppBundle\Twig\Extension\BootstrapGlyph
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension_modal:
        class: AppBundle\Twig\Extension\ModalDialog
        public: false
        tags:
            - { name: twig.extension }
    app.participation_manager:
        class: AppBundle\Manager\ParticipationManager
        arguments: ['@mailer', '@templating']
    app.upload_image_manager:
        class: AppBundle\Manager\UploadImageManager
        arguments: ['%app.upload_image_manager.path%', '%vich_uploader.mappings%']


