# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    app.twig_extension_glyph:
        class: AppBundle\Twig\Extension\BootstrapGlyph
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension_bootstrap_table_filter:
        class: AppBundle\Twig\Extension\BootstrapTableFilter
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension_bitmask:
        class: AppBundle\Twig\Extension\BitMask
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension_modal:
        class: AppBundle\Twig\Extension\ModalDialog
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension_fullname:
        class: AppBundle\Twig\Extension\Fullname
        public: false
        tags:
            - { name: twig.extension }
    app.twig_global_customization:
        class: AppBundle\Twig\GlobalCustomization
        arguments:
            - '@twig'
            - '%kernel.root_dir%'
            - '%customization.app_title%'
            - '%customization.organization_name%'
            - '%customization.organization_address_street%'
            - '%customization.organization_address_postal_code%'
            - '%customization.organization_address_postal_locality%'
            - '%customization.organization_number_phone%'
            - '%customization.organization_number_fax%'
            - '%customization.organization_email%'
            - '%customization.organization_website%'
            - '%customization.organization_facebook%'
            - '%customization.juvem_website%'
    app.twig_mail_generator:
        class: AppBundle\Twig\MailGenerator
        arguments: ['@twig']
    app.participation_manager:
        class: AppBundle\Manager\ParticipationManager
        arguments: ['@mailer', '@app.twig_mail_generator', '@logger']
    app.newsletter_manager:
        class: AppBundle\Manager\NewsletterManager
        arguments: ['@mailer', '@app.twig_mail_generator', '@logger']
    app.upload_image_manager:
        class: AppBundle\Manager\UploadImageManager
        arguments: ['%app.upload_image_manager.path%', '%vich_uploader.mappings%']
    app.user_registration.participation_listener:
        class: AppBundle\EventListeners\UserRegistrationListener
        arguments: ['@doctrine']
        tags:
            - { name: kernel.event_subscriber }

